### ISSUE TITLE
Master panics with "index out of range"

### ISSUE THREAD

**Issue by ninedraft** [tidwall/gjson#125]
Last master revision v1.3.1 dea71f728d5e39c962ed78f3d818b7f1efe7b757 panics when you try to get value by string key, starting with '@'.

```go
var data = `{"@key": "value"}`
gjson.Get(data, "@key")
```
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/tidwall/gjson.Get(0x13b825, 0x16, 0x138aa9, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/tmp/gopath565783212/pkg/mod/github.com/tidwall/gjson@v1.3.1/gjson.go:1856 +0x1040
main.main()
	/tmp/sandbox704585793/prog.go:11 +0x40
```
 
Run example: https://play.golang.org/p/S4xrW9pv0m5

**Comment by tidwall** [comment]
Thanks for reporting this. I just pushed v1.3.2 which fixes the problem.
