### ISSUE TITLE
Map() triggers runtime "index out of range" error

### ISSUE THREAD

**Issue by thisisaaronland** [tidwall/gjson#38]
This code:

https://github.com/whosonfirst/go-whosonfirst-geojson-v2/blob/master/properties/whosonfirst/whosonfirst.go#L299-L309

Is invoking this code:

https://github.com/tidwall/gjson/blob/master/gjson.go#L270-L277

When processing this file:

https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/master/data/101/958/375/101958375.geojson

Resulting in this:

```
2017/08/30 16:34:26 get names for 101958375
panic: runtime error: index out of range

goroutine 13 [running]:
github.com/whosonfirst/go-whosonfirst-geojson-v2/vendor/github.com/tidwall/gjson.unescape(0xc459cbca2e, 0x17, 0x615210, 0x0)
	/usr/local/mapzen/go-whosonfirst-names-tools/src/github.com/whosonfirst/go-whosonfirst-geojson-v2/vendor/github.com/tidwall/gjson/gjson.go:1451 +0x6f3
github.com/whosonfirst/go-whosonfirst-geojson-v2/vendor/github.com/tidwall/gjson.tostr(0xc459cbca2d, 0x576, 0xc459cbca25, 0x7, 0xc459cbca26, 0x5)
	/usr/local/mapzen/go-whosonfirst-names-tools/src/github.com/whosonfirst/go-whosonfirst-geojson-v2/vendor/github.com/tidwall/gjson/gjson.go:559 +0xfc
github.com/whosonfirst/go-whosonfirst-geojson-v2/vendor/github.com/tidwall/gjson.Result.arrayOrMap(0x5, 0xc459cbc400, 0xba3, 0x0, 0x0, 0x0, 0x3a, 0x7b, 0x0, 0x0, ...)
	/usr/local/mapzen/go-whosonfirst-names-tools/src/github.com/whosonfirst/go-whosonfirst-geojson-v2/vendor/github.com/tidwall/gjson/gjson.go:365 +0x714
github.com/whosonfirst/go-whosonfirst-geojson-v2/vendor/github.com/tidwall/gjson.Result.Map(0x5, 0xc459cbc400, 0xba3, 0x0, 0x0, 0x0, 0x3a, 0xba3)
	/usr/local/mapzen/go-whosonfirst-names-tools/src/github.com/whosonfirst/go-whosonfirst-geojson-v2/vendor/github.com/tidwall/gjson/gjson.go:275 +0xbd
github.com/whosonfirst/go-whosonfirst-geojson-v2/properties/whosonfirst.Names(0x604240, 0xc420199cb0, 0x604240)
```

I _think_ I am doing everything to test/handle return values correctly but maybe I am missing something?

**Comment by thisisaaronland** [comment]
We'll update the (WOF) record accordingly. I thought we'd found most of those Unicode issues...
